apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: headlamp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: "nginx"
  rules:
    - host: headlamp.hs.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: headlamp
              port:
                number: 80
