---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advpool
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool-ingress
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-ingress
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.200/24
  avoidBuggyIPs: true
