---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: "kube-prometheus-stack"
    targetRevision: 67.9.0
    helm:
      valueFiles:
      - $values/generic/apps/prometheus-stack/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: "https://github.com/git67/k8s-argocd-bootstrap.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
