---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://projectcapsule.github.io/charts
    chart: "capsule"
    targetRevision: 0.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: capsule-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
