---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp

  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/headlamphttps://kubernetes-sigs.github.io/headlamp/
    chart: "headlamp"
    targetRevision: 0.40.0
    helm:
      valueFiles:
      - $values/generic/apps/headlamp/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: "https://github.com/git67/k8s-argocd-bootstrap.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
