apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: DEV platform and applications

  sourceRepos:
    - https://github.com/git67/k8s-argocd-bootstrap.git

  destinations:

    - server: https://kubernetes.default.svc
      namespace: argocd

    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: ""
      kind: Namespace
