---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: "cert-manager"
    targetRevision: 1.19.1
    helm:
      valueFiles:
      - $values/generic/initial/cert-manager/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: "https://github.com/git67/k8s-argocd-bootstrap.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
