---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-oss
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://helm.nginx.com/stable
    chart: "nginx-ingress"
    targetRevision: 2.3.1
    helm:
      valueFiles:
      - $values/generic/initial/nginx-ingress-oss/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: "https://github.com/git67/k8s-argocd-bootstrap.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
